version: '3.7'
services:
    zookeeper:
      image: wurstmeister/zookeeper
      container_name: spring_zookeper_example
      ports:
        - "2181:2181"
    kafka:
      image: wurstmeister/kafka:2.13-2.7.0
      container_name: spring_kafka_example
      ports:
        - "9092:9092"
      environment:
        KAFKA_ADVERTISED_HOST_NAME: localhost
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_CREATE_TOPICS: "order_request:6:6"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      depends_on:
      - zookeeper